### PR TITLE
Patch `Lighting.Clocktime` to serialize

### PR DESCRIPTION
**Pull request by Dekkonot**
Like it says on the tin.

### CODE REVIEW

**Comment by kennethloeffler** [comment]
I'm a little lost here - did `Lighting.ClockTime` used to serialize? Does Roblox actually read and set this property on deserialization? Are there any related reports for e.g. Rojo or Lune?

**Comment by Dekkonot** [comment]
So, I was in a hurry when I made this PR and didn't provide as much background as I should have.

Rojo has gotten intermittent reports of `ClockTime` not being serialized (see https://github.com/rojo-rbx/rojo/issues/655 for an example), so this just makes it serialize. It doesn't seem like it's ever been serialized by Roblox, but they deserialize it just fine and have since it was introduced.

Another solution would be to provide a migration of some sort for `ClockTime` to `TimeOfDay`, though I'm not sure how necessary it is. It's unlikely someone will have multiple instances of `Lighting` in a file so there's no compatibility concern.

**Comment by kennethloeffler** [comment]
Not sure about this one, tbh. 

I could totally see someone deserializing a place using Lune, (`Lighting.TimeOfDay` will exist in this case), then setting `Lighting.ClockTime`. Both properties will then exist and not be consistent with each other, similar to the concern I had in #302 with `Workspace.CollisionGroups` and `Workspace.CollisionGroupData`, except probably a lot more likely because the value formats for these lighting properties are a lot more approachable, and it's common for people to use them interchangeably. Can we test what Roblox does on deserialization when `Lighting.TimeOfDay` and `Lighting.ClockTime` are both serialized into the same file?

**Comment by Dekkonot** [comment]
In what can only be described as cursed, Roblox seems to load whichever property appears first in the file. This means `ClockTime` when we build it ourselves.

Given this, I'm not sure what to do. A migration would probably work, though I'm not sure how Rojo would handle a file that had both if migrations were involved.

**Review by kennethloeffler — APPROVED** [review]
I think it's fine to serialize both until #277 is more fleshed out... the possible inconsistency kinda sucks, but hopefully it won't be too surprising to users

**Pull request merged**
